server:
  port: 8081

spring:
  application:
    name: flight-service
  datasource:
    url: jdbc:postgresql://localhost:5433/flight_db
    username: flight
    password: flight_pass
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      sentinel:
        master: mymaster
        nodes: localhost:26379
  grpc:
    server:
      port: 9090

grpc:
  auth:
    api-key: ${GRPC_AUTH_API_KEY:default-dev-key}

logging:
  level:
    org.ilynosov.flight: DEBUG

