server:
  port: 8080

spring:
  application:
    name: hw6-producer-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${app.schema-registry-url}

app:
  schema-registry-url: http://localhost:8081
  kafka:
    warehouse-events-topic: warehouse-events

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
